# ----------------------spring---------------------
server:
  port: 8080
  # 开发环境配置
  # 访问路径
  servlet:
    context-path: /
  # 服务模块 热部署开关
spring:
  application:
    name: waimai
  devtools:
    remote:
      restart:
        enabled: true
# --------------------数据源配置-----------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/waimai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root
  redis:
    client-name: localhost
    password: hxzy
    host: localhost
    database: 2
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# -------------------日志配置------------------------
logging:
  level:
    org:
      example: debug
      springframework: warn

mybatis-plus:
    global-config:
      banner: false
# -------------------PageHelper分页插件------------------------
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: countSql
#  # --------------------mybatis-----------------------
#  # 搜索指定包别名
#mybatis.type-aliases-package=com.example
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#mybatis.mapper-locations=classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#mybatis.config-location=classpath:mybatis-config.xml
