# 应用名称
spring:
  application:
    name: eureka-client
# 端口号
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8761,http://eureka02:8762,http://eureka03:8763
    register-with-eureka: true # 可以不注册到eureka
    fetch-registry: true # 是否拉取服务列表（不拉找不到其他人）
    registry-fetch-interval-seconds: 10 # 重新拉取服务列表间隔
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true # 启用ip显示
    lease-renewal-interval-in-seconds: 5 # 续约间隔
