# ----------------------spring---------------------
server:
  port: 8080
  # 开发环境配置
  # 访问路径
  servlet:
    context-path: /

spring:
  application:
    name: waimai
  devtools:
    remote:
      restart:
        enabled: true
  # --------------------数据源配置-----------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root
  redis:
    client-name: localhost
    password: hxzy
    host: localhost
    database: 2
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
# -------------------日志配置------------------------
logging:
  level:
    org:
      example: debug
      springframework: warn

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 控制台打印出sql日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
